name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_prod:
    if: github.ref == 'refs/heads/main' # Deploy only on main
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku (Production)
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "kevin@crowdchat.ca"
          usedocker: true
